---
openapi: 3.0.1
info:
  title: API V1
  version: v1
components:
  securitySchemes:
    bearer_auth:
      type: http
      scheme: bearer
  schemas:
    sample_schema:
      type: object
      properties:
        success:
          type: boolean
        newId:
          type: integer
paths:
  "/reservations":
    post:
      summary: Creates New Reservation
      tags:
      - Reservations
      parameters: []
      responses:
        '201':
          description: Reservation created successfully
          content: {}
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                host:
                  type: integer
                recipient:
                  type: integer
                event_date:
                  type: string
                start_time:
                  type: string
                  description: 24 h time. Ex 16:35 to represent 4:35pm
                end_time:
                  type: string
                  description: 24 h time. Ex 16:35 to represent 4:35pm
                kind:
                  type: string
                  enum:
                    play: 0
                    lesson: 1
                    train: 2
                recipient_rsvp:
                  type: string
                  enum:
                    'yes': 0
                    'no': 1
                    maybe: 2
                note:
                  type: string
    get:
      summary: Get list of reservations with Filters
      tags:
      - Reservations
      parameters:
      - name: host
        in: query
        schema:
          type: integer
      - name: recipient
        in: query
        schema:
          type: integer
      - name: recipient_rsvp
        in: query
        enum:
          'yes': 0
          'no': 1
          maybe: 2
        schema:
          type: string
      - name: start_timestamp
        in: query
        schema:
          type: integer
      responses:
        '200':
          description: Get list of reservations
          content: {}
  "/reservations/{id}":
    put:
      summary: Update Reservation
      tags:
      - Reservations
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
      responses:
        '200':
          description: Reservation updated successfully
          content: {}
        '404':
          description: Reservation update failure with invalid id
          content: {}
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                event_date:
                  type: string
                start_time:
                  type: string
                  description: 24 h time. Ex 16:35 to represent 4:35pm
                end_time:
                  type: string
                  description: 24 h time. Ex 16:35 to represent 4:35pm
                kind:
                  type: string
                  enum:
                    play: 0
                    lesson: 1
                    train: 2
                recipient_rsvp:
                  type: string
                  enum:
                    'yes': 0
                    'no': 1
                    maybe: 2
                note:
                  type: string
    delete:
      summary: Delete a Reservation
      tags:
      - Reservations
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
      responses:
        '204':
          description: Reservation deleted successfully
          content: {}
    get:
      summary: Get a reservation by its ID
      tags:
      - Reservations
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
      responses:
        '200':
          description: Reservation retrieved successfully
          content: {}
  "/schedules":
    post:
      summary: Creates New Schedule for an ORG
      tags:
      - Schedule
      parameters: []
      responses:
        '201':
          description: Schedule created successfully
          content: {}
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                user_id:
                  type: integer
                org_id:
                  type: integer
                hours:
                  type: object
                  properties:
                    monday:
                      type: object
                      properties:
                        start:
                          type: string
                          example: '0800'
                        end:
                          type: string
                          example: '2000'
                        enabled:
                          type: boolean
                          default: true
                    tuesday:
                      type: object
                      properties:
                        start:
                          type: string
                          example: '0800'
                        end:
                          type: string
                          example: '2000'
                        enabled:
                          type: boolean
                          default: true
                    wednesday:
                      type: object
                      properties:
                        start:
                          type: string
                          example: '0800'
                        end:
                          type: string
                          example: '2000'
                        enabled:
                          type: boolean
                          default: true
                    thursday:
                      type: object
                      properties:
                        start:
                          type: string
                          example: '0800'
                        end:
                          type: string
                          example: '2000'
                        enabled:
                          type: boolean
                          default: true
                    friday:
                      type: object
                      properties:
                        start:
                          type: string
                          example: '0800'
                        end:
                          type: string
                          example: '2000'
                        enabled:
                          type: boolean
                          default: true
                    saturday:
                      type: object
                      properties:
                        start:
                          type: string
                          example: '0800'
                        end:
                          type: string
                          example: '2000'
                        enabled:
                          type: boolean
                          default: true
                    sunday:
                      type: object
                      properties:
                        start:
                          type: string
                          example: '0800'
                        end:
                          type: string
                          example: '2000'
                        enabled:
                          type: boolean
                          default: true
                availability_per_interval:
                  type: integer
                price_in_cents:
                  type: integer
              required:
              - user_id
              - org_id
              - hours
              - availability_per_interval
              - price_in_cents
  "/schedules/orgs/{org_id}":
    get:
      summary: Get the schedule for the given org
      tags:
      - Schedule
      parameters:
      - name: org_id
        in: path
        required: true
        schema:
          type: integer
      responses:
        '200':
          description: Get schedule for org
          content: {}
        '404':
          description: Fail get schedule for non existing org id
          content: {}
  "/schedules/{id}":
    put:
      summary: Update Schedule
      tags:
      - Schedule
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
      responses:
        '200':
          description: Schedule updated successfully
          content: {}
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                hours:
                  type: object
                  properties:
                    monday:
                      type: object
                      properties:
                        start:
                          type: string
                          example: '0800'
                        end:
                          type: string
                          example: '2000'
                        enabled:
                          type: boolean
                          default: true
                    tuesday:
                      type: object
                      properties:
                        start:
                          type: string
                          example: '0800'
                        end:
                          type: string
                          example: '2000'
                        enabled:
                          type: boolean
                          default: true
                    wednesday:
                      type: object
                      properties:
                        start:
                          type: string
                          example: '0800'
                        end:
                          type: string
                          example: '2000'
                        enabled:
                          type: boolean
                          default: true
                    thursday:
                      type: object
                      properties:
                        start:
                          type: string
                          example: '0800'
                        end:
                          type: string
                          example: '2000'
                        enabled:
                          type: boolean
                          default: true
                    friday:
                      type: object
                      properties:
                        start:
                          type: string
                          example: '0800'
                        end:
                          type: string
                          example: '2000'
                        enabled:
                          type: boolean
                          default: true
                    saturday:
                      type: object
                      properties:
                        start:
                          type: string
                          example: '0800'
                        end:
                          type: string
                          example: '2000'
                        enabled:
                          type: boolean
                          default: true
                    sunday:
                      type: object
                      properties:
                        start:
                          type: string
                          example: '0800'
                        end:
                          type: string
                          example: '2000'
                        enabled:
                          type: boolean
                          default: true
                availability_per_interval:
                  type: integer
                price_in_cents:
                  type: integer
              required:
              - hours
              - availability_per_interval
              - price_in_cents
servers:
- url: http://{defaultHost}
  variables:
    defaultHost:
      default: localhost:3000
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: localhost:3000
- url: https://nameless-spire-32644.herokuapp.com/
